### PR TITLE
Update code snippets in examples

### PR DESCRIPTION
**Pull request by AnhTuDo1998**
This PR is a draft for issue #49 to help update the codes in `examples`. It is an attempt to follow the implementation discussed in #50 . I try to implement a function in `lib.rs` that only return a `Client` with `user_agent` when test profile is activated. 

If the approach is in good direction, I will update the remaining of examples source code.

### CODE REVIEW

**Comment by madninja** [comment]
hmm.. not a fan of the cfg being in a function that's always defined that then panics. 

How about just passing in a user agent in each of the examples?

**Comment by AnhTuDo1998** [comment]
That sounds plausible. If that is the case maybe I will just use something like below for each example?

`let client = Client::new_with_base_url(DEFAULT_BASE_URL.to_string(), "helium-api-rs/test");`

**Comment by madninja** [comment]
> That sounds plausible. If that is the case maybe I will just use something like below for each example?
> 
> `let client = Client::new_with_base_url(DEFAULT_BASE_URL.to_string(), "helium-api-rs/test");`

Yes, and we can even make new_with_base_url easier so that you don't have to call to_stirng on DEFAULT_BASE_URL. 

But lets start with this approach

**Comment by AnhTuDo1998** [comment]
Hi, do you have any feedback so far about the changes?

**Comment by Rsalyme** [comment]
Hey guys I'm new to Rust but if there's anything I can help with let me know.

**Review by madninja — APPROVED** [review]

**Comment by madninja** [comment]
sorry this took a while. It's not been a high priority and I lost sight of it. 

Thanks for your contribution!

**Pull request merged**
